
services:
  plateform-test:
    image: sandjonyves/plateform-test:latest
    # build: .
    container_name: plateform-test
    restart: unless-stopped
    ports:
      - "${PORT}"
    env_file:
      - .env
    # volumes:
    #   - ./data:/app/data
