version: '3.8'

services:
  plateform-test:
    image: sandjonyves/plateform-test:latest
    # build: .
    container_name: plateform-test
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    # volumes:
    #   - ./data:/app/data
